# Generated by Django 4.2.4 on 2023-08-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flower_name", models.CharField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
    ]
