# Generated by Django 4.2.4 on 2023-08-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flower_delivery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vase_name", models.CharField(max_length=40, unique=True)),
                ("image", models.ImageField(upload_to="images")),
                ("price", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="FlowerVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant_of_flower", models.CharField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="images")),
                ("price", models.IntegerField(default=0)),
                (
                    "flower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flower_delivery.flower",
                    ),
                ),
            ],
        ),
    ]
