# Generated by Django 4.2.4 on 2023-08-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flower_delivery", "0003_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
            ],
        ),
    ]
